social: 
    - name: Twitter 
      url: "https://twitter.com/twomeynj"
      pre: "<i class='fab fa-twitter'></i>"

main: 
    - name: Awarders
      url: /awarders
      desc: Browse awarders

    - name: Recipients
      url: /recipients
      desc: Browse recipients

    - name: Challenges
      url: /challenges
      desc: Browse challenges

footer: 
    - name: About
      url: /about
      