- name: NiallOTuama
  user_id: 117474
  awards:
  - name: Asigmatic
    description: >
      This award celebrates high voter variance, that is, images which have split the crowd. The award was originally suggested by
      another user, and can be read about [here](https://www.dpchallenge.com/image.php?IMAGE_ID=1000203). As opposed to many
      other awards, this is deterministic and is awarded to the user that received the highest vote variance amongst the
      submissions.
    image: https://images.dpchallenge.com/images_portfolio/50000-54999/50695/120/Copyrighted_Image_Reuse_Prohibited_1000203.gif
    urls:
      - Copyrighted_Image_Reuse_Prohibited_1000203
      - 1000203

- name: posthumous
  user_id: 50695
  awards:
  - name: Posthumous Blue
    description: >
      Originally, this was simply my favorite shot in a challenge, but eventually I realized that most challenges
      don't have one, that a Posthumous Blue is actually an image that calls to me and demands to be blue.
    image: https://images.dpchallenge.com/images_portfolio/50000-54999/50695/120/Copyrighted_Image_Reuse_Prohibited_1077284.jpg
    urls:
      - Copyrighted_Image_Reuse_Prohibited_1077284
      - blackyak.com/dpc/bluepost
      - blackyak.com/bluepost
      - bluepost
      - 1077284
  - name: Posthumous Red
    description: >
      Originally, this was simply my second favorite shot in a challenge, but now indicates a fierce image that
      demands to be recognized above everything but the blue.
    image: https://images.dpchallenge.com/images_portfolio/50000-54999/50695/120/Copyrighted_Image_Reuse_Prohibited_1077285.jpg
    urls:
      - Copyrighted_Image_Reuse_Prohibited_1077285
      - blackyak.com/dpc/redpost
      - blackyak.com/redpost
      - redpost
      - 1077285
  - name: Posthumous Yellow
    description: >
      Originally, this was simply my third favorite shot in a challenge, but now is an image that warrants individual
      recognition.
    image: https://images.dpchallenge.com/images_portfolio/50000-54999/50695/120/Copyrighted_Image_Reuse_Prohibited_1077286.jpg
    urls:
      - Copyrighted_Image_Reuse_Prohibited_1077286
      - blackyak.com/yellowpost
      - blackyak.com/dpc/yellowpost
      - yellowpost
      - 1077286
  - name: Posthumous Fantasy
    description: >
      An image that I would put in an exhibition if I had a gallery, or that I would print in a literary arts magazine
    image: https://images.dpchallenge.com/images_portfolio/50000-54999/50695/120/Copyrighted_Image_Reuse_Prohibited_1077279.jpg
    urls:
      - Copyrighted_Image_Reuse_Prohibited_1077279
      - blackyak.com/dpc/artpost
      - artpost
      - 1077279
  - name: Posthumous Almost Blue
    description: >
      Photos that deserved a ribbon but for some reason or other didn't get one
    image: https://images.dpchallenge.com/images_portfolio/50000-54999/50695/120/Copyrighted_Image_Reuse_Prohibited_1077283.gif
    urls:
      - Copyrighted_Image_Reuse_Prohibited_1077283
      - blackyak.com/dpc/almostblue
      - 1077283
  - name: Posthumous Blur
    description: >
      Hot fuzz.
    image: https://images.dpchallenge.com/images_portfolio/50000-54999/50695/120/Copyrighted_Image_Reuse_Prohibited_1077281.jpg
    urls:
      - Copyrighted_Image_Reuse_Prohibited_1077281
      - blackyak.com/dpc/blurpost
      - 1077281
  - name: Posthumous Boo
    description: >
      So good it's scary
    image: https://images.dpchallenge.com/images_portfolio/50000-54999/50695/120/Copyrighted_Image_Reuse_Prohibited_1077280.jpg
    urls:
      - Copyrighted_Image_Reuse_Prohibited_1077280
      - blackyak.com/dpc/boopost
      - 1077280

- name: vawendy
  user_id: 103142
  awards:
  - name: Bluebird of Happiness
    description: >
      I've wanted to create an award like those in the posthumous thread. So this is the "bluebird of happiness" award. If goes to
      pictures that I think are wonderful, help me see things in a different way, or ones that simply make me smile.
    image: https://images.dpchallenge.com/images_portfolio/100000-104999/103142/120/Copyrighted_Image_Reuse_Prohibited_811107.jpg
    urls:
      - Copyrighted_Image_Reuse_Prohibited_811107
      - 811107

- name: vlado
  user_id: 32011
  awards:
    - name: MUAIMHO
      description: Most under-appreciated in my honest opinion
      image: https://images.dpchallenge.com/images_portfolio/30000-34999/32011/120/Copyrighted_Image_Reuse_Prohibited_858386.png
      urls:
        - Copyrighted_Image_Reuse_Prohibited_
        - 858386

- name: neat
  user_id: 114285
  awards:
    - name: Verineat image
      description: For those images that make me sigh!
      image: https://images.dpchallenge.com/images_portfolio/110000-114999/114285/120/Copyrighted_Image_Reuse_Prohibited_1070026.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_1070026
        - Copyrighted_Image_Reuse_Prohibited_1014169
        - 1070026
        - 1014169

- name: chromeydome
  user_id: 82985
  thumb: https://images.dpchallenge.com/images_profile/120_nopicture.png
  awards:
    - name: Post Lumy Award
      description: >
        Nominations go to LUMINOUS images (often overlooked). I can't limit choices to 3 "ribbons" so this "Nomination" approach lets
        me recognize more images
      image: https://images.dpchallenge.com/images_portfolio/80000-84999/82985/120/Copyrighted_Image_Reuse_Prohibited_677021.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_677021
        - 677021

- name: bvy
  user_id: 76335
  awards:
    - name: queen
      description: ''
      image: https://images.dpchallenge.com/images_portfolio/75000-79999/76335/120/Copyrighted_Image_Reuse_Prohibited_1155366.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_1155366
        - 1155366
    - name: spleencourt
      description: ''
      image: https://images.dpchallenge.com/images_portfolio/50000-54999/50641/120/Copyrighted_Image_Reuse_Prohibited_1156027.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_1156027
        - 1156027

- name: yanko
  user_id: 41337
  thumb: https://images.dpchallenge.com/images_profile/120_nopicture.png
  awards:
    - name: yanko blue
      description: Awarded to photos that best exemplifies photography as an art form in a challenge.
      image: https://images.dpchallenge.com/images_portfolio/40000-44999/41337/120/Copyrighted_Image_Reuse_Prohibited_657188.gif
      urls:
        - Copyrighted_Image_Reuse_Prohibited_657188
        - 657188
    - name: yanko red
      description: Awarded to photos that best exemplifies photography as an art form in a challenge.
      image: https://images.dpchallenge.com/images_portfolio/40000-44999/41337/120/Copyrighted_Image_Reuse_Prohibited_657189.gif
      urls:
        - Copyrighted_Image_Reuse_Prohibited_657189
        - 657189
    - name: yanko yellow
      description: Awarded to photos that best exemplifies photography as an art form in a challenge.
      image: https://images.dpchallenge.com/images_portfolio/40000-44999/41337/120/Copyrighted_Image_Reuse_Prohibited_657190.gif
      urls:
        - Copyrighted_Image_Reuse_Prohibited_657190
        - 657190
    - name: yanko green
      description: Awarded to photos that best exemplifies photography as an art form in a challenge.
      image: https://images.dpchallenge.com/images_portfolio/40000-44999/41337/120/Copyrighted_Image_Reuse_Prohibited_657191.gif
      urls:
        - Copyrighted_Image_Reuse_Prohibited_657191
        - 657191

- name: mitalapo
  user_id: 61396
  awards:
    - name: blue balloon
      description: ''
      image: https://images.dpchallenge.com/images_portfolio/60000-64999/61396/120/Copyrighted_Image_Reuse_Prohibited_1154420.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_1154420
        - 1154420
    - name: red balloon
      description: ''
      image: https://images.dpchallenge.com/images_portfolio/60000-64999/61396/120/Copyrighted_Image_Reuse_Prohibited_1154419.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_1154419
        - 1154419
    - name: yellow balloon
      description: ''
      image: https://images.dpchallenge.com/images_portfolio/60000-64999/61396/120/Copyrighted_Image_Reuse_Prohibited_1154421.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_1154421
        - 1154421
#    - name: brown icon
#      description: ''
#      image: https://images.dpchallenge.com/images_portfolio/60000-64999/61396/120/Copyrighted_Image_Reuse_Prohibited_1191530.jpg
#      urls:
#        - Copyrighted_Image_Reuse_Prohibited_1191530
#        - 1191530

- name: tate
  user_id: 38032
  awards:
    - name: Breaking Rad
      description: ''
      image: https://images.dpchallenge.com/images_portfolio/35000-39999/38032/120/Copyrighted_Image_Reuse_Prohibited_1174300.png
      urls:
        - Copyrighted_Image_Reuse_Prohibited_1174300
        - 1174300

- name: Paul
  user_id: 100393
  awards:
    - name: Unconventional Eye
      description: >
        Worth a Longer Look?This award is given to an image that I think was taken with an unconventional eye and has
        more to offer than its final score might suggest.I humbly invite interested viewers to take a longer look and
        see if the image grows on them at all.
      image: https://images.dpchallenge.com/images_portfolio/100000-104999/100393/120/Copyrighted_Image_Reuse_Prohibited_859062.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_859062
        - 859062
    - name: Forward Movement
      description: >
          This is an 'icon' image to replace my 'Longer Look' award. This award the 'Forward Movement' is given to the image
          that I think best takes the DPC community portfolio of images forward.This image is taken from the 'In the Style of
          Nixter': One of the best challenges we have had for interesting images.
      image: https://images.dpchallenge.com/images_portfolio/100000-104999/100393/120/Copyrighted_Image_Reuse_Prohibited_1051747.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_1051747
        - 1051747

- name: bspurgeon
  user_id: 54645
  awards:
    - name: Sterling Sturgeon
      description: Going forward, I'll post the recipients here as a pseudo-gallery as well as the posthumous thread.
      image: https://images.dpchallenge.com/images_portfolio/50000-54999/54645/120/Copyrighted_Image_Reuse_Prohibited_963227.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_963227
        - 963227

- name: ubique
  user_id: 30364
  awards:
    - name: The Thumb
      description: ''
      image: https://images.dpchallenge.com/images_portfolio/30000-34999/30364/120/Copyrighted_Image_Reuse_Prohibited_800078.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_800078
        - 800078

- name: GeorgesBogaert
  user_id: 163081
  awards:
    - name: DRAGONBlue
      description: ''
      image: https://images.dpchallenge.com/images_portfolio/160000-164999/163081/120/Copyrighted_Image_Reuse_Prohibited_1173261.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_1173261
        - 1173261
    - name: DRAGONRed
      description: ''
      image: https://images.dpchallenge.com/images_portfolio/160000-164999/163081/120/Copyrighted_Image_Reuse_Prohibited_1173262.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_1173262
        - 1173262
    - name: DRAGONYellow
      description: ''
      image: https://images.dpchallenge.com/images_portfolio/160000-164999/163081/120/Copyrighted_Image_Reuse_Prohibited_1173263.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_1173263
        - 1173263

- name: Bear_Music
  user_id: 30861
  awards:
    - name: golden bear
      description: ''
      image: https://images.dpchallenge.com/images_portfolio/30000-34999/30861/120/Copyrighted_Image_Reuse_Prohibited_762723.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_762723
        - 762723

- name: xianart
  user_id: 53572
  awards:
    - name: X Yellow
      description: >
        The x prize is back, 'cause I'm back. These are for the lowest placers of my highest scores: those who wuz robbed...
      image: https://images.dpchallenge.com/images_portfolio/50000-54999/53572/120/Copyrighted_Image_Reuse_Prohibited_657243.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_657243
        - 657243

- name: undieyatch
  user_id: 3724
  awards:
    - name: undie award
      description: >
        An award created at the request of Posthumous "undie award" - achievement recognition icon for Posthumous Ribbons
        thread or when ever I feel like giving it.The award may be given during voting or after a challenge is completed
        to insure that my highest votes coincide with challenge submissions whose over all score is 5 and below, or under 50%.
      image: https://images.dpchallenge.com/images_portfolio/0-4999/3724/120/Copyrighted_Image_Reuse_Prohibited_753886.jpg
      urls:
        - Copyrighted_Image_Reuse_Prohibited_753886
        - 753886

- name: jagar
  user_id: 113156
  awards:
    - name: be there blue
      description: ''
      image: https://images.dpchallenge.com/images_portfolio/110000-114999/113156/120/Copyrighted_Image_Reuse_Prohibited_1153614.jpg
      urls:
        - 1153614
    - name: be there red
      description: ''
      image: https://images.dpchallenge.com/images_portfolio/110000-114999/113156/120/Copyrighted_Image_Reuse_Prohibited_1153615.jpg
      urls:
        - 1153615
    - name: be there yellow
      description: ''
      image: https://images.dpchallenge.com/images_portfolio/110000-114999/113156/120/Copyrighted_Image_Reuse_Prohibited_1153616.jpg
      urls:
        - 1153616