-- comments for challenge 3686
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
INSERT INTO comments ("id", "image_id", "commenter_id", "raw_comment", "comment", "date", "edited", "made_during_challenge") VALUES
(7760324, 1285315, 6804, '<td valign="top">This is a wonderful entry for this challenge.  It clearly shows YOUR space, and the mess that surrounds the work area when creating todays feed.  The finished product is no doubt a work of art, but the process is messy. Nobody ever gets to see the work or the effort that goes into the candlelight meal at the end of the week.  Here it is, in living color.  This is one of my favorite photos of this really weird challenge. I can relate to the mess and the effort.  I would love to see a photo of the finished meal. Its tough to make a shot like this appeal to the masses.  I do hope this does well in the challenge.  High marks from me.</td>', 'This is a wonderful entry for this challenge.  It clearly shows YOUR space, and the mess that surrounds the work area when creating todays feed.  The finished product is no doubt a work of art, but the process is messy. Nobody ever gets to see the work or the effort that goes into the candlelight meal at the end of the week.  Here it is, in living color.  This is one of my favorite photos of this really weird challenge. I can relate to the mess and the effort.  I would love to see a photo of the finished meal. Its tough to make a shot like this appeal to the masses.  I do hope this does well in the challenge.  High marks from me.', '2023-11-24 01:08:16.000000', NULL, 1),
(7760325, 1285303, 6804, '<td valign="top">This is a very real space in everyones garage cabinets.  The random chaos is perfect for the way I think of this challenge.  My only question would be your choice of a Black and white version of the image.  Black/white is often used to cut down the chaos of color in an image.  I think the color version might have been just a little louder and more chaotic. Its hard to imagine the color image. As a presentation goes, B/W is probably a more attractive presentation.  But as chaos goes, let the colors scream!  I still gave you high marks for a great entry for this challenge.  Good luck!</td>', 'This is a very real space in everyones garage cabinets.  The random chaos is perfect for the way I think of this challenge.  My only question would be your choice of a Black and white version of the image.  Black/white is often used to cut down the chaos of color in an image.  I think the color version might have been just a little louder and more chaotic. Its hard to imagine the color image. As a presentation goes, B/W is probably a more attractive presentation.  But as chaos goes, let the colors scream!  I still gave you high marks for a great entry for this challenge.  Good luck!', '2023-11-24 01:17:49.000000', NULL, 1),
(7760329, 1285270, 6804, '<td valign="top">This image just makes me smile. I keep coming back to look at it again. What a wonderful glimpse into your daily chaos.  I see the two culprits on the couch at the far end of the room.  I love the non-vertical walls and door frames.  (It helps add to the chaotic feel of the shot).  High marks from me, good luck in the challenge.</td>', 'This image just makes me smile. I keep coming back to look at it again. What a wonderful glimpse into your daily chaos.  I see the two culprits on the couch at the far end of the room.  I love the non-vertical walls and door frames.  (It helps add to the chaotic feel of the shot).  High marks from me, good luck in the challenge.', '2023-11-24 01:59:43.000000', NULL, 1),
(7760346, 1285316, 67145, '<td valign="top">loving the bat .. ;)</td>', 'loving the bat .. ;)', '2023-11-24 18:50:58.000000', NULL, 1),
(7760471, 1285316, 42733, '<td valign="top">My favorite in this challenge.</td>', 'My favorite in this challenge.', '2023-11-28 16:23:47.000000', NULL, 1),
(7760472, 1285314, 42733, '<td valign="top">My pick for red in this challenge.</td>', 'My pick for red in this challenge.', '2023-11-28 16:23:57.000000', NULL, 1),
(7760473, 1285233, 42733, '<td valign="top">My pick for yellow in this challenge.</td>', 'My pick for yellow in this challenge.', '2023-11-28 16:24:11.000000', NULL, 1),
(7760474, 1285107, 42733, '<td valign="top">My kind of mess! :)</td>', 'My kind of mess! :)', '2023-11-28 16:24:22.000000', NULL, 1),
(7760487, 1285233, 6804, '<td valign="top">I like this rendition of YOUR space. The lighting is warm and natural. The image is real, and not contrived to fit the challenge. I can see you struggled to get the image square to the frame. I had the same challenge. The image I see through the view-finder is not exactly the same as the lens is actually shooting.  (And we can''t crop it to make it even). Anyone who hasn''t actually tried to shoot for the minimal editing challenge simply couldn''t appreciate the off-center crop, or the burst of light showing on only a few books in the row.  I hope your entry does well in the challenge.  Great job!, High marks from me.</td>', 'I like this rendition of YOUR space. The lighting is warm and natural. The image is real, and not contrived to fit the challenge. I can see you struggled to get the image square to the frame. I had the same challenge. The image I see through the view-finder is not exactly the same as the lens is actually shooting.  (And we can''t crop it to make it even). Anyone who hasn''t actually tried to shoot for the minimal editing challenge simply couldn''t appreciate the off-center crop, or the burst of light showing on only a few books in the row.  I hope your entry does well in the challenge.  Great job!, High marks from me.', '2023-11-28 23:22:57.000000', NULL, 1),
(7760488, 1285284, 6804, '<td valign="top">This is a pretty cool image, by itself.  As far as meeting the challenge.. I''m having a hard time seeing how this become''s YOUR space. The title "Litter" ..... I don''t see any litter.  You''ve done a great job with the minimal edditing here, but I just can''t rate this awesome image as high as some of the other images that had a much more direct way of defining the "your Space" part of the challenge. I do hope this is helpful and I hope the shot does well in the challenge. Good luck with it!</td>', 'This is a pretty cool image, by itself.  As far as meeting the challenge.. I''m having a hard time seeing how this become''s YOUR space. The title "Litter" ..... I don''t see any litter.  You''ve done a great job with the minimal edditing here, but I just can''t rate this awesome image as high as some of the other images that had a much more direct way of defining the "your Space" part of the challenge. I do hope this is helpful and I hope the shot does well in the challenge. Good luck with it!', '2023-11-28 23:25:02.000000', NULL, 1),
(7760490, 1285316, 97225, '<td valign="top">I love this! What a fabulous collection of stuff. Top pick.</td>', 'I love this! What a fabulous collection of stuff. Top pick.', '2023-11-28 23:31:24.000000', NULL, 1),
(7760491, 1285107, 97225, '<td valign="top">What''s messy about it?</td>', 'What''s messy about it?', '2023-11-28 23:32:45.000000', NULL, 1),
(7760492, 1285233, 97225, '<td valign="top">Not very messy.</td>', 'Not very messy.', '2023-11-28 23:33:27.000000', NULL, 1),
(7760549, 1285316, 63398, '<td valign="top">Stellar! Nicely done. Congrats on your blue.</td>', 'Stellar! Nicely done. Congrats on your blue.', '2023-12-01 00:15:11.000000', NULL, 0),
(7760550, 1285316, 67145, '<td valign="top">many congratulations on the blue .. <br/>was a challenge made for messy folks and collectors .. lol .. <br/>like i said .. i love the bat .. :)</td>', 'many congratulations on the blue .. was a challenge made for messy folks and collectors .. lol .. like i said .. i love the bat .. :)', '2023-12-01 00:21:10.000000', NULL, 0),
(7760551, 1285314, 67145, '<td valign="top">even from above and not seeing your face i felt was 99.9% a Tiberius photo during voting .. <br/>many congratulations on the ribbon and a great view of your mess .. <br/>a mess after all can be a thing of beauty .. ;)</td>', 'even from above and not seeing your face i felt was 99.9% a Tiberius photo during voting .. many congratulations on the ribbon and a great view of your mess .. a mess after all can be a thing of beauty .. ;)', '2023-12-01 00:23:15.000000', NULL, 0),
(7760552, 1285314, 67145, '<td valign="top">just add to my comment .. <br/>a mess can be thing of beauty and tell an excellent and interesting story .. :)</td>', 'just add to my comment .. a mess can be thing of beauty and tell an excellent and interesting story .. :)', '2023-12-01 00:23:54.000000', NULL, 0),
(7760553, 1285299, 67145, '<td valign="top">and here''s me thinking you planned this and stopped all leaf and debris cleaning just for this shot .. lol .. ;)<br/>many congrats on the ribbon Lydia .. its a great shot .. :)</td>', 'and here''s me thinking you planned this and stopped all leaf and debris cleaning just for this shot .. lol .. ;)many congrats on the ribbon Lydia .. its a great shot .. :)', '2023-12-01 00:25:17.000000', NULL, 0),
(7760554, 1285316, 141319, '<td valign="top">Congrats on the blue!<br/></td>', 'Congrats on the blue!', '2023-12-01 03:30:24.000000', NULL, 0),
(7760555, 1285299, 141319, '<td valign="top">Great picture - the universe made the pump stop so you could take the picture :-)</td>', 'Great picture - the universe made the pump stop so you could take the picture :-)', '2023-12-01 03:32:34.000000', NULL, 0),
(7760556, 1285302, 141319, '<td valign="top">I LIKE this shot. Well done.</td>', 'I LIKE this shot. Well done.', '2023-12-01 03:37:16.000000', NULL, 0),
(7760557, 1285277, 141319, '<td valign="top">Loooove the name "mouse pad corner" :-) So, so cute</td>', 'Loooove the name "mouse pad corner" :-) So, so cute', '2023-12-01 03:38:51.000000', NULL, 0),
(7760565, 1285316, 97225, '<td valign="top">Congratulations on the blue. I love looking through your fabulous pieces. (Btw, I have that bat.)</td>', 'Congratulations on the blue. I love looking through your fabulous pieces. (Btw, I have that bat.)', '2023-12-01 05:52:14.000000', NULL, 0),
(7760576, 1285316, 30049, '<td valign="top">I really enjoy the collection and find it interesting, but I''m missing the "messy" part - seems very organized and in order.  ???</td>', 'I really enjoy the collection and find it interesting, but I''m missing the "messy" part - seems very organized and in order.  ???', '2023-12-01 07:43:20.000000', NULL, 0),
(7760578, 1285316, 50695, '<td valign="top"><table align="center" width="95%"><tr><td><div class="textsm"><b>Originally posted by glad2badad:</b></div><hr/><i> I really enjoy the collection and find it interesting, but I''m missing the "messy" part - seems very organized and in order.  ??? </i></td></tr></table> <br/> <br/>the DPC voter hates a mess.</td>', 'Originally posted by glad2badad: I really enjoy the collection and find it interesting, but I''m missing the "messy" part - seems very organized and in order.  ???   the DPC voter hates a mess.', '2023-12-01 11:03:03.000000', NULL, 0),
(7760591, 1285314, 30982, '<td valign="top">Hi Tibi!  How did you get the phone up there??</td>', 'Hi Tibi!  How did you get the phone up there??', '2023-12-01 17:52:49.000000', NULL, 0),
(7760592, 1285316, 122678, '<td valign="top">Congratulations! Great collection of things.</td>', 'Congratulations! Great collection of things.', '2023-12-01 18:52:42.000000', NULL, 0),
(7760593, 1285314, 122678, '<td valign="top">Congratulations, A birds eye view</td>', 'Congratulations, A birds eye view', '2023-12-01 18:53:23.000000', NULL, 0),
(7760594, 1285299, 122678, '<td valign="top">Congratulations, very clever</td>', 'Congratulations, very clever', '2023-12-01 18:54:05.000000', NULL, 0),
(7760595, 1285314, 8759, '<td valign="top"><table align="center" width="95%"><tr><td><div class="textsm"><b>Originally posted by Melethia:</b></div><hr/><i> Hi Tibi!  How did you get the phone up there?? </i></td></tr></table> <br/> <br/>I have a pull up bar in the room. I used a clamp and a selfie stick I have for my motorcycle and used the wide angle with the S-pen of the phone as a remote control.</td>', 'Originally posted by Melethia: Hi Tibi!  How did you get the phone up there??   I have a pull up bar in the room. I used a clamp and a selfie stick I have for my motorcycle and used the wide angle with the S-pen of the phone as a remote control.', '2023-12-01 19:31:34.000000', NULL, 0),
(7760599, 1285189, 68504, '<td valign="top">I didn''t enter this challenge because it would have been too revealing.  This is the only entry I can identify with. For a long time our dining room table served as a temporary project of whatever kind work space. Temporary is a long long word.  And I put things there simply to compete, to lay claim to some space. Internecine warfare.</td>', 'I didn''t enter this challenge because it would have been too revealing.  This is the only entry I can identify with. For a long time our dining room table served as a temporary project of whatever kind work space. Temporary is a long long word.  And I put things there simply to compete, to lay claim to some space. Internecine warfare.', '2023-12-02 00:25:34.000000', NULL, 0),
(7760707, 1285314, 30982, '<td valign="top"><table align="center" width="95%"><tr><td><div class="textsm"><b>Originally posted by Tiberius:</b></div><hr/><i> <table align="center" width="95%"><tr><td><div class="textsm"><b>Originally posted by Melethia:</b></div><hr/><i> Hi Tibi!  How did you get the phone up there?? </i></td></tr></table> <br/> <br/>I have a pull up bar in the room. I used a clamp and a selfie stick I have for my motorcycle and used the wide angle with the S-pen of the phone as a remote control. </i></td></tr></table> <br/>Ah, very good!  Mine is the lesser S22 so I don''t have the pen/remote option.  I am always in awe of the ways you find to work your magic with your phone!</td>', 'Originally posted by Tiberius: Originally posted by Melethia: Hi Tibi!  How did you get the phone up there??   I have a pull up bar in the room. I used a clamp and a selfie stick I have for my motorcycle and used the wide angle with the S-pen of the phone as a remote control.  Ah, very good!  Mine is the lesser S22 so I don''t have the pen/remote option.  I am always in awe of the ways you find to work your magic with your phone!', '2023-12-04 19:08:58.000000', NULL, 0);
COMMIT;
