"""initial schema

Revision ID: 986e64120e3c
Revises:
Create Date: 2026-09-05 09:13:13.328958
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "986e64120e3c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "challenge_probes",
        sa.Column("challenge_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("checked_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("challenge_id"),
    )
    op.create_table(
        "challenges",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("submission_start", sa.Date(), nullable=False),
        sa.Column("submission_end", sa.Date(), nullable=False),
        sa.Column("voting_start", sa.Date(), nullable=False),
        sa.Column("voting_end", sa.Date(), nullable=False),
        sa.Column("num_submissions", sa.Integer(), nullable=False),
        sa.Column("num_disqualifications", sa.Integer(), nullable=False),
        sa.Column("num_votes", sa.Integer(), nullable=False),
        sa.Column("num_comments", sa.Integer(), nullable=False),
        sa.Column("average_score", sa.Float(), nullable=False),
        sa.Column("highest_score", sa.Float(), nullable=False),
        sa.Column("median_score", sa.Float(), nullable=False),
        sa.Column("lowest_score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("challenges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_challenges_name"), ["name"], unique=False)

    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("join_date", sa.Date(), nullable=True),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_members_name"), ["name"], unique=False)

    op.create_table(
        "awards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("awarder_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("image_src", sa.String(length=512), nullable=False),
        sa.Column("markers", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["awarder_id"], ["members.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("awarder_id", "name", name="uq_award_awarder_name"),
    )
    with op.batch_alter_table("awards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_awards_awarder_id"), ["awarder_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_awards_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_awards_slug"), ["slug"], unique=True)

    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("challenge_id", sa.Integer(), nullable=False),
        sa.Column("photographer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("votes", sa.JSON(), nullable=False),
        sa.Column("disqualified", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("average_all", sa.Float(), nullable=True),
        sa.Column("average_commenters", sa.Float(), nullable=True),
        sa.Column("average_participants", sa.Float(), nullable=True),
        sa.Column("average_non_participants", sa.Float(), nullable=True),
        sa.Column("num_views", sa.Integer(), nullable=True),
        sa.Column("num_votes", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["challenge_id"], ["challenges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["photographer_id"], ["members.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_images_challenge_id"), ["challenge_id"], unique=False)
        batch_op.create_index(
            "ix_images_challenge_score", ["challenge_id", "average_all"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_images_photographer_id"), ["photographer_id"], unique=False
        )

    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("commenter_id", sa.Integer(), nullable=False),
        sa.Column("raw_comment", sa.Text(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("edited", sa.DateTime(), nullable=True),
        sa.Column("made_during_challenge", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["commenter_id"], ["members.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["image_id"], ["images.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_comments_commenter_id"), ["commenter_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_comments_image_id"), ["image_id"], unique=False)

    op.create_table(
        "award_grants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("award_id", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column("comment_id", sa.Integer(), nullable=True),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("challenge_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["award_id"], ["awards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["challenge_id"], ["challenges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["comment_id"], ["comments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["image_id"], ["images.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipient_id"], ["members.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("award_id", "comment_id", name="uq_grant_award_comment"),
        sa.UniqueConstraint("award_id", "image_id", name="uq_grant_award_image"),
    )
    with op.batch_alter_table("award_grants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_award_grants_award_id"), ["award_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_award_grants_challenge_id"), ["challenge_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_award_grants_comment_id"), ["comment_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_award_grants_image_id"), ["image_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_award_grants_recipient_id"), ["recipient_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("award_grants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_award_grants_recipient_id"))
        batch_op.drop_index(batch_op.f("ix_award_grants_image_id"))
        batch_op.drop_index(batch_op.f("ix_award_grants_comment_id"))
        batch_op.drop_index(batch_op.f("ix_award_grants_challenge_id"))
        batch_op.drop_index(batch_op.f("ix_award_grants_award_id"))

    op.drop_table("award_grants")
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comments_image_id"))
        batch_op.drop_index(batch_op.f("ix_comments_commenter_id"))

    op.drop_table("comments")
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_images_photographer_id"))
        batch_op.drop_index("ix_images_challenge_score")
        batch_op.drop_index(batch_op.f("ix_images_challenge_id"))

    op.drop_table("images")
    with op.batch_alter_table("awards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_awards_slug"))
        batch_op.drop_index(batch_op.f("ix_awards_name"))
        batch_op.drop_index(batch_op.f("ix_awards_awarder_id"))

    op.drop_table("awards")
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_members_name"))

    op.drop_table("members")
    with op.batch_alter_table("challenges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_challenges_name"))

    op.drop_table("challenges")
    op.drop_table("challenge_probes")
    # ### end Alembic commands ###
